name: Issue monitor

on:
  issues:
    types: [opened, edited]

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --frozen

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --frozen

      - name: Process command
        run: |
          uv run scripts/main.py process-string "${{ github.event.issue.title }}"
          uv run scripts/main.py render
          echo "Render done"

      - name: commit render
        run: |
          git add data/rendered.png
          git commit -m "Render issue ${{ github.event.issue.title }}"
          git push
